services:
    wowapps.dailymotion:
        class: WowApps\DailymotionBundle\Service\DailymotionService
        arguments:
            - "%wowapps.dailymotion.config%"
            - "%wowapps.dailymotion.fields%"